version: '3.8'

services:
  # MySQL Database Service
  db:
    image: mysql:8.0
    container_name: waste2product_db
    restart: always
    environment:
      MYSQL_DATABASE: waste2product
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - waste2product-network

  # Laravel Application Service
  app:
    build: .
    image: 192.168.56.10:8083/laravelapp:1.0
    container_name: waste2product_app
    restart: always
    working_dir: /var/www/html
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: waste2product
      DB_USERNAME: laravel_user
      DB_PASSWORD: laravel_password
    volumes:
      - .:/var/www/html
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
    depends_on:
      - db
    networks:
      - waste2product-network

  # Nginx Web Server Service
  webserver:
    image: nginx:alpine
    container_name: waste2product_webserver
    restart: always
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - waste2product-network

volumes:
  mysql-data:
    driver: local

networks:
  waste2product-network:
    driver: bridge
